name: RepaintSVD
channels:
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pip:
      - diffusers==0.27.0
      - transformers
      - opencv-python
      - accelerate
      - scikit-image